
language: cpp
sudo: false

compiler:
  - gcc
addons: &clang34
  apt:
    packages:
    # compiler
#      - clang-3.6
      - g++-7
      - gcc-7
      - ninja-build
    # doc tools
      - doxygen
      - graphviz
      # mscgen is currently not whitelisted :(
      #- mscgen
    # third-party dependencies
      - libboost1.55-dev
      - libboost-date-time1.55-dev
      - libboost-log1.55-dev
      - libboost-thread1.55-dev
      - libboost-wave1.55-dev
      - libboost1.55-all-dev
      - libopenal-dev
    sources:
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.6
      - boost-latest

install:
  - gcc-7 --version
#  - clang-3.6 --version
  # install CMake 3.9
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - echo "656dcc6efd777b8a510016fb39603b6b *cmake-3.9.0-Linux-x86_64.tar.gz" > cmake_md5.txt
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.9.0-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.9.0-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/ComicSansMS/GhulbusBase.git gbBase
  - cd gbBase
  - mkdir base-static-gcc7
  - cd base-static-gcc7
  - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DGB_BUILD_TESTS=OFF -DGB_GENERATE_DOXYGEN_DOCUMENTATION=OFF -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/base-static-gcc7_INSTALL ..
  - make && make install
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-static-gcc7 && mkdir build-shared-gcc7 && mkdir build-bare-gcc7 && mkdir build-coverage-gcc7 && mkdir build-static-clang36 && mkdir build-shared-clang36
  - cd build-static-gcc7
  - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DGHULBUS_BASE_ROOT=${TRAVIS_BUILD_DIR}/base-static-gcc7_INSTALL ..
  - make
  - cd ../build-coverage-gcc7
  - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DGB_GENERATE_COVERAGE_INFO=ON -DGCOV_COMMAND=gcov-5 -DGHULBUS_BASE_ROOT=${TRAVIS_BUILD_DIR}/base-static-gcc7_INSTALL ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}/build-static-gcc7
  - make test
  - cd ${TRAVIS_BUILD_DIR}/build-coverage-gcc7
  - make test

after_script:
  - cd ${TRAVIS_BUILD_DIR}/build-static-gcc7
  - make doxygen-doc

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build-coverage-gcc7
  - make gbAudio_TestCoverage
  - bash <(curl -s https://codecov.io/bash)
